# Generated by Django 5.0.6 on 2024-07-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('members', '0009_remove_buyer_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_message', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.buyer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.restaurant')),
            ],
        ),
    ]
