# Generated by Django 5.0.6 on 2024-07-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Deliveryman',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
