# Generated by Django 5.0.6 on 2024-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
