# Generated by Django 5.0.6 on 2024-07-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_buyer_reset_token_deliveryman_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='remaining_stock',
        ),
    ]
