# Generated by Django 5.0.6 on 2024-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_fooditem_remaining_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
