# Generated by Django 5.0.6 on 2024-09-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_buyer_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='password_reset_token',
        ),
    ]
