# Generated by Django 5.0.6 on 2024-09-10 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_buyer_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include letters, numbers, and special characters.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include letters, numbers, and special characters.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include letters, numbers, and special characters.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
    ]
